# Generated by Django 4.1 on 2022-08-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_alter_userdetail_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
