# Generated by Django 4.1 on 2022-08-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_alter_userdetail_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='accept_discplinary_actions',
            field=models.CharField(choices=[('Yes I accept student with previous record of discplinary actions', 'Yes I accept student with previous record of discplinary actions'), ('No I dont prefer student with any previous discplinary actions', 'No I dont prefer student with any previous discplinary actions')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='ethnicity',
            field=models.CharField(choices=[('BRITISH', 'British'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='personality',
            field=models.CharField(choices=[('EXTROVERT', 'Extrovert'), ('INTROVERT', 'Introvert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='time_availibility',
            field=models.CharField(choices=[('ONE TO FIVE HOURS', '1-5 hours per week'), ('MORE THAN FIVE HOURS', 'More than 5 hours')], max_length=30),
        ),
    ]
