# Generated by Django 4.1 on 2022-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_alter_userdetail_accept_discplinary_actions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='accept_discplinary_actions',
            field=models.CharField(choices=[('ACCEPT_YES', 'Yes I accept student with previous record of discplinary actions'), ('ACCEPT_NO', 'No I dont prefer student with any previous discplinary actions')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='discplinary_actions',
            field=models.CharField(choices=[('YES', 'Yes I have previous record of discplinary actions'), ('NO', 'No I dont have any previous discplinary actions')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='mentoring_experience',
            field=models.CharField(choices=[('NO_EXPERIENCE', "I don't have any mentoring experience"), ('ONE_OR_MORE', 'I have mentoring experience')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='teaching_experience',
            field=models.CharField(choices=[('NO_EXPERIENCE', "I don't have any experience"), ('ONE_OR_MORE', 'I have experience')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='time_availibility',
            field=models.CharField(choices=[('ONE_TO_FIVE_HOURS', '1-5 hours per week'), ('MORE_THAN_FIVE_HOURS', 'More than 5 hours')], max_length=30),
        ),
    ]
