# Generated by Django 4.1 on 2022-08-23 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_rename_name_userprofile_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('age', models.IntegerField()),
                ('ethnicity', models.CharField(choices=[('BRITISH', 'British'), ('OTHER', 'Other')], max_length=20)),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('SPANISH', 'Spanish'), ('OTHER', 'Other')], max_length=20)),
                ('personality', models.CharField(choices=[('EXTROVERT', 'Extrovert'), ('INTROVERT', 'Introvert')], max_length=20)),
                ('faculty', models.CharField(choices=[('SCIENCE_AND_TECH', 'Science and Technology'), ('OTHER', 'Other')], max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles_api.basemodel')),
                ('teaching_experience', models.CharField(choices=[('NO_EXPERIENCE', "I don't have any experience"), ('ONE_OR_MORE', 'I have experience')], max_length=30)),
                ('mentoring_experience', models.CharField(choices=[('NO_EXPERIENCE', "I don't have any mentoring experience"), ('ONE_OR_MORE', 'I have mentoring experience')], max_length=30)),
                ('time_availibility', models.CharField(choices=[('ONE_TO_FIVE_HOURS', '1-5 hours per week'), ('MORE_THAN_FIVE_HOURS', 'More than 5 hours')], max_length=30)),
                ('accept_discplinary_actions', models.CharField(choices=[('ACCEPT_YES', 'Yes I accept student with previous record of discplinary actions'), ('ACCEPT_NO', 'No I dont prefer student with any previous discplinary actions')], max_length=255)),
            ],
            bases=('profiles_api.basemodel',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles_api.basemodel')),
                ('discplinary_actions', models.CharField(choices=[('YES', 'Yes I have previous record of discplinary actions'), ('NO', 'No I dont have any previous discplinary actions')], max_length=255)),
                ('grade', models.CharField(max_length=255)),
            ],
            bases=('profiles_api.basemodel',),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
        migrations.AddField(
            model_name='mentor',
            name='student',
            field=models.ManyToManyField(to='profiles_api.student'),
        ),
    ]
