# Generated by Django 4.1 on 2022-08-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_basemodel_mentor_student_delete_userdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='student',
        ),
    ]
