# Generated by Django 4.1 on 2022-08-31 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_remove_mentor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='mentor_or_mentee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_or_mentee', to=settings.AUTH_USER_MODEL),
        ),
    ]
