# Generated by Django 4.1 on 2022-09-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_basemodel_first_name_basemodel_last_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
    ]
